-- Run this in your Supabase project (SQL Editor) to create the waitlist table.

CREATE TABLE IF NOT EXISTS public.waitlist (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL UNIQUE,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.waitlist ENABLE ROW LEVEL SECURITY;

-- Allow anyone to insert (for signup); no read for anon if you want to keep list private.
CREATE POLICY "Allow public insert on waitlist"
  ON public.waitlist
  FOR INSERT
  WITH CHECK (true);

-- Optional: allow authenticated admin to read (create an admin role and use it).
-- CREATE POLICY "Allow admin read" ON public.waitlist FOR SELECT USING (auth.role() = 'admin');
